.PHONY: clean All

All:
	@echo "----------Building project:[ sec8_challenge - Debug ]----------"
	@cd "sec8_challenge" && "$(MAKE)" -f  "sec8_challenge.mk"
clean:
	@echo "----------Cleaning project:[ sec8_challenge - Debug ]----------"
	@cd "sec8_challenge" && "$(MAKE)" -f  "sec8_challenge.mk" clean
